In [1]:
import pandas as pd
import numpy as np

In [2]:
outbound_data = pd.read_parquet('/data/alexander.huang/data/0903_data/outbound_proc_test_mod.parq')
inbound_data = pd.read_parquet('/data/alexander.huang/data/0903_data/inbound_proc_test_mod.parq')

In [3]:
outbound_data

,inside_ip_len,inside_ip_dst_LAT,inside_ip_dst_LONG,inside_ip_ttl,inside_tcp_win_size,packet_label,inside_ip_protocol_0,inside_ip_protocol_1,inside_ip_protocol_103,inside_ip_protocol_17,...,inside_port_dst_80,inside_port_dst_812,inside_port_dst_853,inside_port_dst_88,inside_port_dst_938,inside_port_dst_992,inside_port_dst_993,inside_port_dst_995,inside_port_dst_997,inside_port_dst_unseen
index,,,,,,,,,,,,,,,,,,,,,
60000,-0.186277,0.094858,0.131170,0.242140,-0.055801,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60001,-0.213596,-0.071807,0.081984,0.242620,-0.053281,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60002,0.367937,-0.088679,-0.183373,-0.278571,0.004336,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60003,-0.207061,0.043909,-0.199570,-0.293544,-0.039681,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
60004,0.389087,-0.098048,0.296013,-0.258956,-0.048755,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7199995,-0.208713,-0.070166,0.080109,-0.295885,-0.049250,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7199996,-0.199707,0.259867,-0.163900,-0.283118,-0.051610,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7199997,-0.155966,0.330941,-0.192028,0.226139,0.004615,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7199998,-0.140162,-0.071012,0.081076,-0.299456,-0.055527,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7199999,-0.157061,-0.112337,0.292139,-0.284985,-0.052844,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [4]:
outbound_data.index

Index([  60000,   60001,   60002,   60003,   60004,   60005,   60006,   60007,
         60008,   60009,
       ...
       7199990, 7199991, 7199992, 7199993, 7199994, 7199995, 7199996, 7199997,
       7199998, 7199999],
      dtype='int64', name='index', length=3585962)

In [5]:
# import raw data
in_raw = pd.read_parquet('/data/alexander.huang/data/0903_data/inbound_read_test.parq')
out_raw = pd.read_parquet('/data/alexander.huang/data/0903_data/outbound_read_test.parq')

In [6]:
in_raw

,packet_label,outside_timestamp,outside_ip_protocol,outside_ip_len,outside_ip_src,outside_ip_dst,outside_port_src,outside_port_dst,outside_tcp_win_size,outside_tcp_flags,...,inside_timestamp,inside_ip_protocol,inside_ip_len,inside_ip_src,inside_ip_dst,inside_port_src,inside_port_dst,inside_tcp_win_size,inside_tcp_flags,inside_ip_ttl
index,,,,,,,,,,,,,,,,,,,,,
0,0,1.670868e+09,17,1266,2714209182,3449504226,8801,49268,0,0,...,1.670868e+09,17,1266,2714209182,2887032038,8801,64150,0,0,53
1,0,1.670868e+09,6,1454,887092956,3449504226,443,24336,2420,24,...,1.670868e+09,6,1454,887092956,2887020829,443,59435,2420,24,56
2,0,1.670868e+09,6,1406,3116854937,3449504226,443,31782,294,16,...,1.670868e+09,6,1406,3116854937,2887028785,443,51418,294,16,58
3,0,1.670868e+09,6,1406,3116854937,3449504226,443,31782,294,16,...,1.670868e+09,6,1406,3116854937,2887028785,443,51418,294,16,58
4,0,1.670868e+09,6,1406,399282960,3449504226,80,27458,501,16,...,1.670868e+09,6,1406,399282960,2887031166,80,57986,501,16,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7139995,0,1.670872e+09,6,1500,878735778,3449504226,443,41073,16384,16,...,1.670872e+09,6,1500,878735778,2887020828,443,65389,16384,16,240
7139996,0,1.670872e+09,6,83,878748738,3449504226,443,49778,16385,24,...,1.670872e+09,6,83,878748738,2887014683,443,64825,16385,24,240
7139997,0,1.670872e+09,6,1500,1159504384,3449504226,80,37031,64664,16,...,1.670872e+09,6,1500,1159504384,2887004436,80,53157,64664,16,57
7139998,0,1.670872e+09,17,1178,879828246,3449504226,3480,52573,0,0,...,1.670872e+09,17,1123,879828246,2887016710,3480,50035,0,0,109
7139999,0,1.670872e+09,6,1406,1091083825,3449504226,443,11303,135,16,...,1.670872e+09,6,1406,1091083825,2887030864,443,56145,135,16,242

In [7]:
out_raw

,packet_label,outside_timestamp,outside_ip_protocol,outside_ip_len,outside_ip_src,outside_ip_dst,outside_port_src,outside_port_dst,outside_tcp_win_size,outside_tcp_flags,...,inside_timestamp,inside_ip_protocol,inside_ip_len,inside_ip_src,inside_ip_dst,inside_port_src,inside_port_dst,inside_tcp_win_size,inside_tcp_flags,inside_ip_ttl
index,,,,,,,,,,,,,,,,,,,,,
60000,0,1.670868e+09,6,40,3449504226,880755727,4429,443,1022,16,...,1.670868e+09,6,100,2887017345,880755727,60830,443,1022,24,127
60001,0,1.670868e+09,6,40,3449504226,2398826154,11655,443,12355,16,...,1.670868e+09,6,40,2887016828,2398826154,54310,443,12355,16,127
60002,0,1.670868e+09,6,1406,3449504226,301528430,8087,443,262144,16,...,1.670868e+09,6,1406,2887028986,301528430,51402,443,262144,16,63
60003,0,1.670868e+09,6,40,3449504226,3334292014,2684,443,65535,16,...,1.670868e+09,6,40,2887004837,3334292014,51364,443,65535,16,63
60004,0,1.670868e+09,6,1500,3429295176,1141570384,443,50102,3197,16,...,1.670868e+09,6,1500,3429295176,1141570384,443,50102,3197,16,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7199995,0,1.670872e+09,6,40,3449504226,2398797252,17218,443,24752,16,...,1.670872e+09,6,40,2887029185,2398797252,51748,443,24752,16,63
7199996,0,1.670872e+09,6,40,3449504226,873156406,9847,443,4091,16,...,1.670872e+09,6,40,2887028846,873156406,52103,443,4091,16,63
7199997,0,1.670872e+09,6,143,3449504226,340836060,25528,443,263168,24,...,1.670872e+09,6,143,2887004834,340836060,51725,443,263168,24,127
7199998,1,0.000000e+00,0,0,0,0,0,0,0,0,...,1.670872e+09,17,200,2886997844,214068165,37046,26824,0,0,63
7199999,1,0.000000e+00,0,0,0,0,0,0,0,0,...,1.670872e+09,17,144,2887009164,880755079,50050,3480,0,0,63

In [8]:
in_idx = inbound_data.index.tolist()
print(len(in_idx))

3583199

In [9]:
out_idx = outbound_data.index.tolist()
print(len(out_idx))

3585962

In [10]:
out_raw_idx = out_raw.index.tolist()
in_raw_idx = in_raw.index.tolist()

In [11]:
print(len(out_raw_idx))
print(len(in_raw_idx))

3600000
3600000

In [12]:
out_diff = list(set(out_raw_idx)-set(out_idx))
print(len(out_diff))

14038

In [13]:
in_diff = list(set(in_raw_idx)-set(in_idx))
print(len(in_diff))

16801

In [14]:
in_df = in_raw.drop(in_diff)

In [15]:
len(in_df)

3583199

In [16]:
out_df = out_raw.drop(out_diff)
len(out_df)

3585962

In [17]:
# save in_df and out_df
# outbound dnn uncertainty
out_uncert = pd.read_parquet('/home/alexander.huang/repositories/huang-thesis/models/cd_uncertainty_.parq')
print(len(out_uncert))

3585962

In [18]:
# load model predictions for concrete dropout
cd_pred = np.load('/smallwork/alexander.huang/concrete_dropout/outbound/49114892/predictions.npy')

In [19]:
cd_probs = np.mean(cd_pred, axis=0)

In [20]:
cd_probs.shape

(3585962, 2)

In [21]:
threshold = 0.5123641
cd_classes = np.where(cd_probs[:,1] > threshold, 1, 0)
print(cd_classes)
print(np.unique(cd_classes, return_counts=True))

[0 0 0 ... 0 1 0]
(array([0, 1]), array([3486231,   99731]))

In [22]:
out_df['concrete dropout w/ threshold prediction'] = cd_classes

In [23]:
out_df.iloc[1304]

packet_label                                1.000000e+00
outside_timestamp                           0.000000e+00
outside_ip_protocol                         0.000000e+00
outside_ip_len                              0.000000e+00
outside_ip_src                              0.000000e+00
outside_ip_dst                              0.000000e+00
outside_port_src                            0.000000e+00
outside_port_dst                            0.000000e+00
outside_tcp_win_size                        0.000000e+00
outside_tcp_flags                           0.000000e+00
outside_ip_ttl                              0.000000e+00
inside_timestamp                            1.670868e+09
inside_ip_protocol                          1.700000e+01
inside_ip_len                               2.000000e+02
inside_ip_src                               2.886998e+09
inside_ip_dst                               2.179076e+08
inside_port_src                             3.922200e+04
inside_port_dst                             3.228600e+04
inside_tcp_win_size                         0.000000e+00
inside_tcp_flags                            0.000000e+00
inside_ip_ttl                               6.300000e+01
concrete dropout w/ threshold prediction    1.000000e+00
Name: 61306, dtype: float64

In [24]:
out_df

,packet_label,outside_timestamp,outside_ip_protocol,outside_ip_len,outside_ip_src,outside_ip_dst,outside_port_src,outside_port_dst,outside_tcp_win_size,outside_tcp_flags,...,inside_ip_protocol,inside_ip_len,inside_ip_src,inside_ip_dst,inside_port_src,inside_port_dst,inside_tcp_win_size,inside_tcp_flags,inside_ip_ttl,concrete dropout w/ threshold prediction
index,,,,,,,,,,,,,,,,,,,,,
60000,0,1.670868e+09,6,40,3449504226,880755727,4429,443,1022,16,...,6,100,2887017345,880755727,60830,443,1022,24,127,0
60001,0,1.670868e+09,6,40,3449504226,2398826154,11655,443,12355,16,...,6,40,2887016828,2398826154,54310,443,12355,16,127,0
60002,0,1.670868e+09,6,1406,3449504226,301528430,8087,443,262144,16,...,6,1406,2887028986,301528430,51402,443,262144,16,63,0
60003,0,1.670868e+09,6,40,3449504226,3334292014,2684,443,65535,16,...,6,40,2887004837,3334292014,51364,443,65535,16,63,0
60004,0,1.670868e+09,6,1500,3429295176,1141570384,443,50102,3197,16,...,6,1500,3429295176,1141570384,443,50102,3197,16,64,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7199995,0,1.670872e+09,6,40,3449504226,2398797252,17218,443,24752,16,...,6,40,2887029185,2398797252,51748,443,24752,16,63,0
7199996,0,1.670872e+09,6,40,3449504226,873156406,9847,443,4091,16,...,6,40,2887028846,873156406,52103,443,4091,16,63,0
7199997,0,1.670872e+09,6,143,3449504226,340836060,25528,443,263168,24,...,6,143,2887004834,340836060,51725,443,263168,24,127,0
7199998,1,0.000000e+00,0,0,0,0,0,0,0,0,...,17,200,2886997844,214068165,37046,26824,0,0,63,1
7199999,1,0.000000e+00,0,0,0,0,0,0,0,0,...,17,144,2887009164,880755079,50050,3480,0,0,63,0

In [25]:
out_uncert

         Epistemic Uncertainty  Aleatoric Uncertainty  Total Uncertainty
0                     0.000083               0.028187           0.028270
1                     0.000079               0.025622           0.025702
2                     0.000103               0.058110           0.058214
3                     0.000136               0.042048           0.042184
4                     0.000042               0.005226           0.005268
...                        ...                    ...                ...
3585957               0.000231               0.046231           0.046463
3585958               0.000457               0.050353           0.050811
3585959               0.000198               0.026906           0.027104
3585960               0.001317               0.688670           0.689988
3585961               0.003238               0.689878           0.693117

[3585962 rows x 3 columns]

In [26]:
out_uncert.set_index(out_df.index, inplace=True)

In [27]:
out_final = pd.concat([out_df, out_uncert], axis=1)

In [28]:
print(out_final.columns)

Index(['packet_label', 'outside_timestamp', 'outside_ip_protocol',
       'outside_ip_len', 'outside_ip_src', 'outside_ip_dst',
       'outside_port_src', 'outside_port_dst', 'outside_tcp_win_size',
       'outside_tcp_flags', 'outside_ip_ttl', 'inside_timestamp',
       'inside_ip_protocol', 'inside_ip_len', 'inside_ip_src', 'inside_ip_dst',
       'inside_port_src', 'inside_port_dst', 'inside_tcp_win_size',
       'inside_tcp_flags', 'inside_ip_ttl',
       'concrete dropout w/ threshold prediction', 'Epistemic Uncertainty',
       'Aleatoric Uncertainty', 'Total Uncertainty'],
      dtype='object')

In [29]:
outside_features = ['outside_timestamp', 
                    'outside_ip_protocol', 
                    'outside_ip_len', 
                    'outside_ip_src', 
                    'outside_ip_dst', 
                    'outside_port_src',
                   'outside_port_dst',
                   'outside_tcp_win_size',
                   'outside_tcp_flags',
                   'outside_ip_ttl']

out_final.drop(outside_features, axis=1, inplace=True)

In [30]:
out_final

,packet_label,inside_timestamp,inside_ip_protocol,inside_ip_len,inside_ip_src,inside_ip_dst,inside_port_src,inside_port_dst,inside_tcp_win_size,inside_tcp_flags,inside_ip_ttl,concrete dropout w/ threshold prediction,Epistemic Uncertainty,Aleatoric Uncertainty,Total Uncertainty
index,,,,,,,,,,,,,,,
60000,0,1.670868e+09,6,100,2887017345,880755727,60830,443,1022,24,127,0,0.000083,0.028187,0.028270
60001,0,1.670868e+09,6,40,2887016828,2398826154,54310,443,12355,16,127,0,0.000079,0.025622,0.025702
60002,0,1.670868e+09,6,1406,2887028986,301528430,51402,443,262144,16,63,0,0.000103,0.058110,0.058214
60003,0,1.670868e+09,6,40,2887004837,3334292014,51364,443,65535,16,63,0,0.000136,0.042048,0.042184
60004,0,1.670868e+09,6,1500,3429295176,1141570384,443,50102,3197,16,64,0,0.000042,0.005226,0.005268
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7199995,0,1.670872e+09,6,40,2887029185,2398797252,51748,443,24752,16,63,0,0.000231,0.046231,0.046463
7199996,0,1.670872e+09,6,40,2887028846,873156406,52103,443,4091,16,63,0,0.000457,0.050353,0.050811
7199997,0,1.670872e+09,6,143,2887004834,340836060,51725,443,263168,24,127,0,0.000198,0.026906,0.027104
7199998,1,1.670872e+09,17,200,2886997844,214068165,37046,26824,0,0,63,1,0.001317,0.688670,0.689988
7199999,1,1.670872e+09,17,144,2887009164,880755079,50050,3480,0,0,63,0,0.003238,0.689878,0.693117

In [31]:
out_final.to_parquet('outbound_concrete_dropout_predictions.parq')

In [32]:
out_final.iloc[1304]

packet_label                                1.000000e+00
inside_timestamp                            1.670868e+09
inside_ip_protocol                          1.700000e+01
inside_ip_len                               2.000000e+02
inside_ip_src                               2.886998e+09
inside_ip_dst                               2.179076e+08
inside_port_src                             3.922200e+04
inside_port_dst                             3.228600e+04
inside_tcp_win_size                         0.000000e+00
inside_tcp_flags                            0.000000e+00
inside_ip_ttl                               6.300000e+01
concrete dropout w/ threshold prediction    1.000000e+00
Epistemic Uncertainty                       2.768736e-03
Aleatoric Uncertainty                       6.865452e-01
Total Uncertainty                           6.893140e-01
Name: 61306, dtype: float64